apiVersion: v1
kind: Service
metadata:
  name: simplesvc
  namespace: '${ trigger[''user''] }'
spec:
  ports:
    - name: canary
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: reports
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: simple-app
  type: NodePort
