apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: opsmxdeploy
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: opsmxdeploy
  template:
    metadata:
      labels:
        app: opsmxdeploy
    spec:
       containers:
        - image: 'docker.io/opsmx11/restapp:opsmx-gke-cas-v0.1.0'
          imagePullPolicy: Always
          name: opsmxapp
          ports:
            - containerPort: 8090
              name: cas
              protocol: TCP
            - containerPort: 9090
              name: moniter
              protocol: TCP
            - containerPort: 8050
              name: audit
              protocol: TCP
            - containerPort: 8161
              name: reports
              protocol: TCP
       
